apiVersion: v1
kind: Namespace
metadata: 
  name: curso-contenedores
  labels:
    app: curso-contenedores
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curso-contenedores
  namespace: curso-contenedores
  labels:
    app: curso-contenedores
spec:
  replicas: 10
  selector:
    matchLabels:
      app: curso-contenedores
  template:
    metadata:
      labels:
         app: curso-contenedores
    spec:
      containers:
        - name: curso-contenedores
          image: carlosmarind/curso-contenedores:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
